### ISSUE TITLE
OK to swap the 100nF caps for 4.7uF? 

### ISSUE THREAD

**Issue by dturner** [FrankBoesing/memoryboard#1]
Hi Frank. Thanks for sharing this awesome little board design. A quick question if you don't mind. I accidentally used 4.7uF capacitors instead of 100nF. The test script runs successfully but I'm wondering whether I should swap them for 100nF?

**Comment by FrankBoesing** [comment]
Hi Don, the capacitors are meant as blocking caps for the RAMs- their value is not that important I think - but 4.7uF is really a lot more than in the datasheet. On the other hand, if it works...

**Comment by dturner** [comment]
OK thanks Frank, I'll leave as is. If the RAM chips blow up I'll update this ticket :)
